# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# --- 1. AUMENTAR LA MEMORIA RAM PARA GRADLE ---
# Por defecto viene en 2048m (2GB). Lo subimos a 4GB (4096m) y le damos más espacio de caché (MaxMetaspaceSize)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# --- 2. ACELERAR LA CONSTRUCCIÓN (TRUE MAGICS) ---
# Compilar varios módulos a la vez en paralelo
org.gradle.parallel=true

# Guardar en caché lo que ya está compilado para no volver a hacerlo
org.gradle.caching=true

# Configurar solo los proyectos necesarios (ahorra tiempo)
org.gradle.configureondemand=false

# --- 3. CONFIGURACIONES DE ANDROID ---
# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Reduce the size of the R class
android.nonTransitiveRClass=true